import type { Metadata } from "next";
import localFont from "next/font/local";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const graphik = localFont({
  src: [
    {
      path: "./fonts/Graphik-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Graphik-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Graphik-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Graphik-Semibold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Graphik-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-graphik",
});


const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "800", "900"],
  variable: "--font-libre-franklin",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Briko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libreFranklin.variable} ${graphik.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
